### PR TITLE
Only link restricted method doc-file if it is available

### PR DESCRIPTION
**Pull request by hns**
This only creates the link to the restricted methods doc file if package `java.lang` is included in the documentation. The test no longer disables link checks, but now the link is not covered by the test.

### CODE REVIEW

**Comment by pavelrappo** [comment]
So it's not a dependent PR in the JDK sense, it's a PR against another PR. Interesting; never seen one before, I think.

**Review by pavelrappo — COMMENTED** [review]
This looks much better than the target PR, but I also think we should figure out how to test the link.

**Review by mcimadamore — APPROVED** [review]
Nice! Thanks.

**Comment by mcimadamore** [comment]
> So it's not a dependent PR in the JDK sense, it's a PR against another PR. Interesting; never seen one before, I think.

We did a few with complex changes in FFM integrations :-)

**Comment by mcimadamore** [comment]
> This looks much better than the target PR, but I also think we should figure out how to test the link.

I agree it would be better if that could be tested too - on the other hand, I think we're now discussing about stuff that probably is outside the scope of this PR. E.g. maybe it would be better to add a separate and more general issue on how to test links that have such bi-modal behavior?

**Comment by hns** [comment]
> I agree it would be better if that could be tested too - on the other hand, I think we're now discussing about stuff that probably is outside the scope of this PR. E.g. maybe it would be better to add a separate and more general issue on how to test links that have such bi-modal behavior?

Sounds good to me. I'll file a follow-up issue.

**Pull request merged**
